repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Use latest stable version
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/pylint
    rev: v3.1.0  # Use a stable version
    hooks:
      - id: pylint
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
